#!/usr/bin/env bash
# Script Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
mkdir -p /var/www/html
sudo service nginx start
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
SERVER_CONFIG=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
		rewrite ^ https://sketchfab.com/bluepeno/models permanent;
	}
}"
bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"
sudo service nginx restart
