#!/usr/bin/env bash
# displays best school 10 times using a while loop
# on 9th iteration, displays 'hi' before 'best school

count=0

while [ $count -lt 10 ]
do
if [$count -eq 9 ]
then
echo "Hi"
fi
echo "Best School"
(( count++ ))
done
